# Generated by Django 4.1.7 on 2023-05-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tisch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nummer", models.PositiveIntegerField()),
                ("capacity", models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("datum", models.DateField()),
                ("uhrzeit", models.TimeField()),
                ("anzahl", models.PositiveIntegerField()),
                ("email", models.CharField(default="", max_length=256)),
                ("telnum", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tisch",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="portal.tisch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kunde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lieferadresse", models.CharField(max_length=512)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gericht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("beschreibung", models.TextField()),
                ("preis", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="gerichte/"),
                ),
                (
                    "kategorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.kategorie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bestellung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(auto_now_add=True)),
                ("gesamtsumme", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("gerichte", models.ManyToManyField(to="portal.gericht")),
                (
                    "kunde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.kunde"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bestellposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menge", models.IntegerField()),
                ("preis", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "bestellung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.bestellung",
                    ),
                ),
                (
                    "gericht",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.gericht"
                    ),
                ),
            ],
        ),
    ]
