# Generated by Django 4.1.7 on 2023-05-06 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0002_alter_bestellung_datum_alter_bestellung_gesamtsumme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kunde",
            name="user",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
